/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  appliedStepsCount: Generated<number>;
  checksum: string;
  finishedAt: Timestamp | null;
  id: string;
  logs: string | null;
  migrationName: string;
  rolledBackAt: Timestamp | null;
  startedAt: Generated<Timestamp>;
}

export interface Shohin {
  hanbaiTanka: number | null;
  shiireTanka: number | null;
  shohinBunrui: string;
  shohinId: string;
  shohinMei: string;
  torokubi: Timestamp | null;
}

export interface ShohinBunrui {
  shohinBunrui: string;
  sumHanbaiTanka: number | null;
  sumShiireTanka: number | null;
}

export interface ShohinCopy {
  hanbaiTanka: number | null;
  shiireTanka: number | null;
  shohinBunrui: string;
  shohinId: string;
  shohinMei: string;
  torokubi: Timestamp | null;
}

export interface ShohinIns {
  hanbaiTanka: Generated<number | null>;
  shiireTanka: number | null;
  shohinBunrui: string;
  shohinId: string;
  shohinMei: string;
  torokubi: Timestamp | null;
}

export interface ShohinSaeki {
  hanbaiTanka: number | null;
  saeki: number | null;
  shiireTanka: number | null;
  shohinId: string;
  shohinMei: string;
}

export interface DB {
  _PrismaMigrations: _PrismaMigrations;
  shohin: Shohin;
  shohinBunrui: ShohinBunrui;
  shohinCopy: ShohinCopy;
  shohinIns: ShohinIns;
  shohinSaeki: ShohinSaeki;
}
