/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  appliedStepsCount: Generated<number>;
  checksum: string;
  finishedAt: Timestamp | null;
  id: string;
  logs: string | null;
  migrationName: string;
  rolledBackAt: Timestamp | null;
  startedAt: Generated<Timestamp>;
}

export interface Posts {
  authorId: number;
  content: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  published: Generated<boolean>;
  title: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  name: string | null;
}

export interface DB {
  _PrismaMigrations: _PrismaMigrations;
  posts: Posts;
  users: Users;
}
